defaults:
  - data: glami
  - models: text_model
  - optimizer: sgd_optimizer
  - scheduler: constant_scheduler
  - callbacks: minimal 
  - logger: csv
  - trainer: glami 
  - paths: glami
  - hydra: default
  - _self_

project: "mm-gfun"
task_name: dryrun 

vision_model:
  base_model: google/vit-base-patch16-224

text_model:
  base_model: xlm-roberta-base

data:
  batch_size: 64
  num_workers: 6
  skip_images: True

trainer:
  accelerator: gpu
  accumulate_grad_batches: 8