defaults:
  - _self_
  - data: glami
  - models: vision_model
  - optimizer: sgd_optimizer
  - scheduler: constant_scheduler
  - callbacks: minimal 
  - logger: csv
  - trainer: glami 
  - paths: glami
  - hydra: default
  - experiment: null
  - debug: null

num_labels: 191

project: "mm-gfun"
task_name: train

vision_model:
  base_model: google/vit-base-patch16-224

text_model:
  base_model: xlm-roberta-base